version: '3.1'

services:
    wildfly:
        build:
            context: .
            args:
              ADMIN_USER: dockerfly
              ADMIN_PASS: dockerfly
        image: nderwin/docker-wildfly:10.1.0.Final.3
        container_name: docker-wildfly
        hostname: docker-wildfly
        ports:
          - "8080:8080"
          - "9990:9990"
